"""Init tables

Revision ID: 8bea09e2d0d4
Revises:
Create Date: 2026-07-15 23:08:00.603343

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8bea09e2d0d4"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column(
            "created_by", sqlmodel.sql.sqltypes.AutoString(length=55), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "updated_by", sqlmodel.sql.sqltypes.AutoString(length=55), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_categories_category_id"), "categories", ["category_id"], unique=True
    )
    op.create_index(op.f("ix_categories_id"), "categories", ["id"], unique=False)
    op.create_index(op.f("ix_categories_title"), "categories", ["title"], unique=True)
    op.create_table(
        "medias",
        sa.Column(
            "created_by", sqlmodel.sql.sqltypes.AutoString(length=55), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "updated_by", sqlmodel.sql.sqltypes.AutoString(length=55), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "media_id", sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False
        ),
        sa.Column(
            "file_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "file_type", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_medias_id"), "medias", ["id"], unique=False)
    op.create_index(op.f("ix_medias_media_id"), "medias", ["media_id"], unique=True)
    op.create_table(
        "articles",
        sa.Column(
            "created_by", sqlmodel.sql.sqltypes.AutoString(length=55), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "updated_by", sqlmodel.sql.sqltypes.AutoString(length=55), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "article_id", sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False
        ),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("sources", sa.JSON(), nullable=True),
        sa.Column(
            "state",
            sa.Enum(
                "DRAFT",
                "SUBMITTED",
                "PENDING",
                "CORRECTION_REQUESTED",
                "APPROVED",
                "PUBLISHED",
                name="status",
            ),
            nullable=False,
        ),
        sa.Column("likes", sa.Integer(), nullable=False),
        sa.Column("dislikes", sa.Integer(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("admin_review", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("cover_image_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["cover_image_id"],
            ["medias.media_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_articles_admin_review"), "articles", ["admin_review"], unique=False
    )
    op.create_index(
        op.f("ix_articles_article_id"), "articles", ["article_id"], unique=True
    )
    op.create_index(op.f("ix_articles_id"), "articles", ["id"], unique=False)
    op.create_index(op.f("ix_articles_state"), "articles", ["state"], unique=False)
    op.create_index(op.f("ix_articles_title"), "articles", ["title"], unique=False)
    op.create_index(op.f("ix_articles_user_id"), "articles", ["user_id"], unique=False)
    op.create_table(
        "article_categories",
        sa.Column("article_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("category_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.article_id"],
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.category_id"],
        ),
        sa.PrimaryKeyConstraint("article_id", "category_id"),
    )
    op.create_table(
        "article_medias_gallery",
        sa.Column("article_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("media_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.article_id"],
        ),
        sa.ForeignKeyConstraint(
            ["media_id"],
            ["medias.media_id"],
        ),
        sa.PrimaryKeyConstraint("article_id", "media_id"),
    )
    op.create_table(
        "article_reactions",
        sa.Column(
            "created_by", sqlmodel.sql.sqltypes.AutoString(length=55), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "updated_by", sqlmodel.sql.sqltypes.AutoString(length=55), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "reaction_id", sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False
        ),
        sa.Column(
            "article_id", sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False
        ),
        sa.Column(
            "user_id", sqlmodel.sql.sqltypes.AutoString(length=55), nullable=False
        ),
        sa.Column(
            "reaction", sa.Enum("LIKE", "DISLIKE", name="reactiontype"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.article_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "article_id", "user_id", name="uq_article_reactions_article_user"
        ),
        sa.UniqueConstraint("reaction_id"),
    )
    op.create_index(
        op.f("ix_article_reactions_article_id"),
        "article_reactions",
        ["article_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_article_reactions_id"), "article_reactions", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_article_reactions_reaction"),
        "article_reactions",
        ["reaction"],
        unique=False,
    )
    op.create_index(
        op.f("ix_article_reactions_user_id"),
        "article_reactions",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "comments",
        sa.Column(
            "created_by", sqlmodel.sql.sqltypes.AutoString(length=55), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "updated_by", sqlmodel.sql.sqltypes.AutoString(length=55), nullable=True
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "comment_id", sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False
        ),
        sa.Column(
            "content", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("article_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.article_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("comment_id"),
    )
    op.create_index(op.f("ix_comments_id"), "comments", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_comments_id"), table_name="comments")
    op.drop_table("comments")
    op.drop_index(op.f("ix_article_reactions_user_id"), table_name="article_reactions")
    op.drop_index(op.f("ix_article_reactions_reaction"), table_name="article_reactions")
    op.drop_index(op.f("ix_article_reactions_id"), table_name="article_reactions")
    op.drop_index(
        op.f("ix_article_reactions_article_id"), table_name="article_reactions"
    )
    op.drop_table("article_reactions")
    op.drop_table("article_medias_gallery")
    op.drop_table("article_categories")
    op.drop_index(op.f("ix_articles_user_id"), table_name="articles")
    op.drop_index(op.f("ix_articles_title"), table_name="articles")
    op.drop_index(op.f("ix_articles_state"), table_name="articles")
    op.drop_index(op.f("ix_articles_id"), table_name="articles")
    op.drop_index(op.f("ix_articles_article_id"), table_name="articles")
    op.drop_index(op.f("ix_articles_admin_review"), table_name="articles")
    op.drop_table("articles")
    op.drop_index(op.f("ix_medias_media_id"), table_name="medias")
    op.drop_index(op.f("ix_medias_id"), table_name="medias")
    op.drop_table("medias")
    op.drop_index(op.f("ix_categories_title"), table_name="categories")
    op.drop_index(op.f("ix_categories_id"), table_name="categories")
    op.drop_index(op.f("ix_categories_category_id"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
