"""fix models primary key

Revision ID: 90928eca8567
Revises: 39b192ab3a85
Create Date: 2026-09-09 11:48:58.193443

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "90928eca8567"
down_revision: Union[str, Sequence[str], None] = "39b192ab3a85"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_article_reactions_id"), table_name="article_reactions")
    op.drop_column("article_reactions", "id")
    op.drop_index(op.f("ix_articles_id"), table_name="articles")
    op.drop_column("articles", "id")
    op.drop_index(op.f("ix_comments_id"), table_name="comments")
    op.drop_column("comments", "id")
    op.drop_index(op.f("ix_medias_id"), table_name="medias")
    op.drop_column("medias", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "medias", sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False)
    )
    op.create_index(op.f("ix_medias_id"), "medias", ["id"], unique=False)
    op.add_column(
        "comments", sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False)
    )
    op.create_index(op.f("ix_comments_id"), "comments", ["id"], unique=False)
    op.add_column(
        "articles", sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False)
    )
    op.create_index(op.f("ix_articles_id"), "articles", ["id"], unique=False)
    op.add_column(
        "article_reactions",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    )
    op.create_index(
        op.f("ix_article_reactions_id"), "article_reactions", ["id"], unique=False
    )
    # ### end Alembic commands ###
